# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 17:11
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sap_success_factors', '0002_auto_20170224_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogtransmissionaudit',
            name='end',
        ),
        migrations.RemoveField(
            model_name='catalogtransmissionaudit',
            name='start',
        ),
        migrations.AddField(
            model_name='catalogtransmissionaudit',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='catalogtransmissionaudit',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
